"""Phase 7 of the "Support Bot NLU upgrade" plan — golden-fixture
regression guard. bot/support_bot/testdata/golden_fixtures.json was
generated by running the REAL live Python hybrid classifier over a
curated set of inputs (real training examples, near-threshold/ambiguous
text, and out-of-vocabulary gibberish). This test proves the Python
engine still reproduces them exactly; the Android JVM test
(android-app/app/src/test/kotlin/com/botserver/mobile/nlu/GoldenFixturesTest.kt)
loads the SAME file and proves the Kotlin port agrees, within float
tolerance — together, the hard cross-platform proof the two engines
never silently drift apart.

Regenerate this file only via an explicit maintainer command (re-run the
generation snippet against the live classifier) when training data
genuinely changes — never silently re-baseline it just to make a
failing test pass, since that would defeat the point of a regression
guard.
"""
from __future__ import annotations

import json
from pathlib import Path

from bot.support_bot import hybrid

FIXTURES_PATH = Path(__file__).resolve().parent.parent / "bot" / "support_bot" / "testdata" / "golden_fixtures.json"


def _load_fixtures() -> list[dict]:
    return json.loads(FIXTURES_PATH.read_text(encoding="utf-8"))


def test_golden_fixtures_file_exists_and_is_non_empty():
    fixtures = _load_fixtures()
    assert len(fixtures) > 0


def test_python_engine_reproduces_every_golden_fixture():
    fixtures = _load_fixtures()
    mismatches = []
    for fixture in fixtures:
        result = hybrid.classify(fixture["text"], log=False)
        if result.intent != fixture["expected_intent"] or abs(result.confidence - fixture["expected_confidence"]) > 1e-4:
            mismatches.append((fixture["text"], fixture, result))
    assert not mismatches, f"golden fixture mismatches (Python engine drifted or training data changed): {mismatches}"
